name: hello world

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run echo
        run: echo "Hello, world!"

      - name: Show repository files
        run: ls -la

      - name: Show current date
        run: date

      - name: Finish
        run: echo "GitHub Action completed successfully!"